### ISSUE TITLE
bug: _pb2.py must be regenerated with protoc >= 3.19.0

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/scanoss.py#16]
## Description

Running a freshly installed scanoss-py in the shell causes a _pb2.py file to throw a fatal error.

The stack trace suggests a fix:
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.

It also provides a workaround:
> Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python does get the job done.

## Stack Trace

```
$ scanoss-py -h
Traceback (most recent call last):
  File "/Users/lucasgonze/Library/Python/3.8/bin/scanoss-py", line 5, in <module>
    from scanoss.cli import main
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/scanoss/cli.py", line 29, in <module>
    from .scanner import Scanner
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/scanoss/scanner.py", line 40, in <module>
    from .threadeddependencies import ThreadedDependencies
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/scanoss/threadeddependencies.py", line 32, in <module>
    from .scanossgrpc import ScanossGrpc
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/scanoss/scanossgrpc.py", line 31, in <module>
    from .api.dependencies.v2.scanoss_dependencies_pb2_grpc import DependenciesStub
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/scanoss/api/dependencies/v2/scanoss_dependencies_pb2_grpc.py", line 5, in <module>
    from scanoss.api.common.v2 import scanoss_common_pb2 as scanoss_dot_api_dot_common_dot_v2_dot_scanoss__common__pb2
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/scanoss/api/common/v2/scanoss_common_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Users/lucasgonze/Library/Python/3.8/lib/python/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by eeisegn** [comment]
Hi Lucas,

Can you confirm the version of Python and the protobuf you have installed?

We have setup an installation requirement of the following (for now):

`
install_requires=["requests", "crc32c>=2.2", "binaryornot", "progress", "grpcio<=1.42.0", "protobuf>=3.16.0,<=3.19.1"],
`

Thanks!

**Comment by lucasgonze** [comment]
The Python version is 3.8. The protobuf version is 4.21.8.

**Comment by eeisegn** [comment]
OK.
If you want to use the current (latest) version of `scanoss-py` you need to downgrade `protobuf` to `3.19.1` or run with `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`.

We plan to upgrade to the latest version of `protobuf` in the near future.

Thanks!
