### ISSUE TITLE
Not compatible with python 3.10

### ISSUE THREAD

**Issue by sebastianpfischer** [scanoss/scanoss.py#17]
After doing a `pip install scanoss` and doing a `scanoss-py scan -o scan-output.json .` I get

`
Traceback (most recent call last):
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/bin/scanoss-py", line 5, in <module>
    from scanoss.cli import main
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/scanoss/cli.py", line 29, in <module>
    from .scanner import Scanner
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/scanoss/scanner.py", line 33, in <module>
    from .scanossapi import ScanossApi
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/scanoss/scanossapi.py", line 29, in <module>
    import requests
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/Users/FSC6LR/Library/Caches/pypoetry/virtualenvs/brc3-bootmanager-oss-scan-XgefEgjN-py3.10/lib/python3.10/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
`

I think something is wrong with the dependencies. `Mapping`, starting 3.10 is part of `collection.abc`

**Comment by eeisegn** [comment]
Hi Sebastian,

We will investigate and revert back shortly.

Thanks!

**Comment by eeisegn** [comment]
Hi Sebastian,

What version of `requests` and `urllib3` are you using?
We've tested python 3.10 with urllib3 `1.26.12` & requests `2.28.1` and it works as expected.

Thanks, Sean.

**Comment by sebastianpfischer** [comment]
Hi @eeisegn ,

sorry, it takes some time to collect the needed information:
`
Package            Version
------------------ ---------
binaryornot        0.4.4
certifi            2022.9.24
chardet            5.0.0
charset-normalizer 2.0.12
crc32c             2.3
grpcio             1.42.0
idna               3.4
pip                22.2.2
progress           1.6
protobuf           3.19.1
requests           2.27.1
scanoss            1.1.1
setuptools         65.4.1
six                1.16.0
urllib3            1.22
wheel              0.37.1
`

So no, I do not use the same `request` and `urllib3` libs...

When I use `pipdeptree`, I get:

`
pip==22.2.2
pipdeptree==2.3.3
scanoss==1.1.1
  - binaryornot [required: Any, installed: 0.4.4]
    - chardet [required: >=3.0.2, installed: 5.0.0]
  - crc32c [required: >=2.2, installed: 2.3]
  - grpcio [required: <=1.42.0, installed: 1.42.0]
    - six [required: >=1.5.2, installed: 1.16.0]
  - progress [required: Any, installed: 1.6]
  - protobuf [required: >=3.16.0,<=3.19.1, installed: 3.19.1]
  - requests [required: Any, installed: 2.27.1]
    - certifi [required: >=2017.4.17, installed: 2022.9.24]
    - charset-normalizer [required: ~=2.0.0, installed: 2.0.12]
    - idna [required: >=2.5,<4, installed: 3.4]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.22]
setuptools==65.4.1
wheel==0.37.1
`

So in theory, pip did resolve the dependencies correctly... I guess you need to refine a bit the dependencies instead of 'Any' ?

**Comment by eeisegn** [comment]
Hi,

OK. It looks like the installed version of `urllib3` doesn't support python 3.10 correctly.
We will see if we can require a version of `requests` that satisfies this requirement in a future update.

Thanks!
